AllCops:
  Exclude:
    - db/schema.rb
    - config/routes.rb
    - db/migrate/*.rb
    - Rakefile
    - Gemfile
    - config/**/*
    - bin/spring
    - '**/*.json.jbuilder'
    - bundler/**/*
    - bin/**/*
    - node_modules/**/*
    - tmp/**/*
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  CountComments: true  # count full line comments?
  Max: 15