version: '3.8'

services:
  web:
    container_name: back-end
    build: .
    env_file:
      - env.development
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    # links:
    #   - postgres
    # depends_on:
    #   - postgres
#   postgres:
#     container_name: app-db
#     image: postgres:12.4
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: Vai7Ob0jjoom4At3Ahth3aec
# volumes:
#   postgres-data: